'use client';

import { jsPDF } from 'jspdf';
import { FileText, Download } from 'lucide-react';
import { useStore } from '@/lib/store';
import { format } from 'date-fns';

export default function SitrepGenerator() {
  const incidents = useStore((state) => state.incidents);

  const generatePDF = () => {
    const doc = new jsPDF();
    const today = format(new Date(), 'yyyy-MM-dd HH:mm:ss');

    // Header
    doc.setFillColor(0, 0, 0);
    doc.rect(0, 0, 210, 297, 'F'); // Black background for PDF? Maybe too much ink. Let's stick to white for printability, or dark if digital. Let's do Standard Military style (White).
    
    // Reset to White background for readability
    doc.setFillColor(255, 255, 255);
    doc.rect(0, 0, 210, 297, 'F');

    // Classification
    doc.setFont("courier", "bold");
    doc.setTextColor(255, 0, 0); // Red
    doc.setFontSize(14);
    doc.text("TOP SECRET // NOFORN // GCMS EYES ONLY", 105, 15, { align: "center" });

    // Meta
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(10);
    doc.text(`SITREP GENERATED: ${today}`, 15, 25);
    doc.text(`OPERATIONAL THEATER: GLOBAL`, 15, 30);
    doc.text(`ACTIVE CONFLICTS: ${incidents.length}`, 15, 35);

    // Line
    doc.setDrawColor(0, 0, 0);
    doc.line(15, 40, 195, 40);

    // Critical Intel
    doc.setFontSize(12);
    doc.text("CRITICAL INTELLIGENCE FEED", 15, 50);

    let y = 60;
    const critical = incidents.filter(i => i.severity > 70).slice(0, 15);

    critical.forEach((incident, i) => {
      if (y > 280) {
        doc.addPage();
        y = 20;
      }
      
      const title = `[${incident.type.toUpperCase()}] ${incident.country} (SEV: ${incident.severity})`;
      doc.setFont("courier", "bold");
      doc.text(title, 15, y);
      
      y += 5;
      doc.setFont("courier", "normal");
      doc.setFontSize(9);
      const summaryLines = doc.splitTextToSize(incident.summary, 180);
      doc.text(summaryLines, 15, y);
      
      y += (summaryLines.length * 4) + 5;
    });

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text("GENERATED BY SENTINEL AI SYSTEM", 105, 290, { align: "center" });

    doc.save(`SITREP_${today.replace(/ /g, '_')}.pdf`);
  };

  return (
    <button
      onClick={generatePDF}
      className="flex items-center gap-2 px-3 py-2 bg-primary/10 hover:bg-primary/20 text-primary border border-primary/30 rounded transition-all text-xs font-mono font-bold w-full justify-center group"
    >
      <FileText className="w-4 h-4" />
      <span>GENERATE CLASSIFIED BRIEF</span>
      <Download className="w-3 h-3 group-hover:translate-y-1 transition-transform" />
    </button>
  );
}
